#pragma once

constexpr float

WALKING_SPEED = 0.2f,
SPRINTING_COEF = 1.3f,
SNEAKING_COEF = 0.4f,
SWIMMING_COEF = 0.5f,
FLYING_COEF = 2.55f,
SPRINT_FLYING_COEF = 2.0f,
//SPRINT_FLYING_COEF = 5.0f,

ICE_SPEED = 3.5f,
ICE_SPRINTING_COEF = 2.0f,

DROWNING_SPEED_ON_SURFACE = -0.5f,
DROWNING_SPEED_UNDERWATER = -1.0f,
SWIMMING_VERTICAL_SPEED = 4.0f,

SATURATION_DEFAULT = 5.0f;

constexpr int

MAX_HP = 20,
MAX_HUNGER = 20,
MAX_OXYGEN = 20;